[en]
  title = "Rants and Raves!"
  languageName = "English"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/"
#
#[ko]
#  title = "Hugo Zzo Theme"
#  languageName = "한국어"
#  weight = 2
#  languagedir = "ltr"
#  contentdir = "content/ko"
