[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 1

[[main]]
  identifier = "posts"
  name = "Posts"
  url = "posts"
  weight = 3

[[main]]
  identifier = "categories"
  name = "Categories"
  url = "categories"
  weight = 5

# I don't use tags for my blog, only categories.
#[[main]]
#  identifier = "tags"
#  name = "Tags"
#  url = "tags"
#  weight = 7
